---
- name: setup new Vagrant box with the latest updates and config
  hosts: windows
  gather_facts: no

  pre_tasks:
  - name: get major and minor version of Windows for later tasks
    win_shell: |
      $version = [Environment]::OSVersion.Version
      Write-Host "$($version.Major).$($version.Minor)-$($env:PROCESSOR_ARCHITECTURE)"
    register: os_version

  roles:
  #- update
  #- cleanup-winsxs
  #- cleanup-features
  #- cleanup
  #- sysprep

  # To add
  # Show hidden files
  # Show file extensions
  # Add chocolatey with procmon, procexp, pstools
  # should I run win_dotnet_ngen
