# adds the upload information
---
- name: check that mandatory variables for vagrant-cloud have been set
  assert:
    that:
    - opt_packer_setup_access_token is defined
    - opt_packer_setup_box_tag is defined
    - opt_packer_setup_version is defined

- name: set new value that we want to set for the post-processors section
  set_fact:
    pri_packer_setup_post_processors:
    - type: vagrant
      keep_input_artifact: false
      output: "{{man_packer_setup_host_type}}/{% raw %}{{'{{'}}.Provider{{'}}'}}{% endraw %}.box"
    - type: vagrant-cloud
      access_token: '{{opt_packer_setup_access_token}}'
      box_tag: '{{opt_packer_setup_box_tag}}'
      version: '{{opt_packer_setup_version}}'

- name: override the post-processors section to add the vagrant-cloud processor
  set_fact:
    pri_packer_setup_json: '{{pri_packer_setup_json|update_dict("post-processors", [ pri_packer_setup_post_processors ])}}'
