---
- name: install and enable TLSv1.2 for Server 2008 and 2008 R2
  block:
  - name: enable TLSv1.2 support for Server 2008 and 2008 R2
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\{{item.type}}
      name: '{{item.property}}'
      data: '{{item.value}}'
      type: dword
      state: present
    register: pri_personalise_tls_config
    when: not (man_is_longhorn and item.type == "Server") # Server 2008 Server impl does not work, only apply the client configuration
    loop:
    - type: Server
      property: Enabled
      value: 1
    - type: Server
      property: DisabledByDefault
      value: 0
    - type: Client
      property: Enabled
      value: 1
    - type: Client
      property: DisabledByDefault
      value: 0

  - name: reboot if TLS config was applied
    win_reboot:
    when: pri_personalise_tls_config is changed
  when: man_host_type == '2008-x86' or man_host_type == '2008-x64' or man_host_type == '2008r2'

- name: set show hidden files/folders and file extensions for the default user profile
  win_regedit:
    path: HKLM:\ANSIBLE\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: '{{item.name}}'
    data: '{{item.data}}'
    type: dword
    state: present
    hive: C:\Users\Default\NTUSER.dat
  register: pri_personalise_profile_reg_change
  # seems like this fails to unload in Packer for whatever reason, we don't want to fail if we got that error
  failed_when:
  - pri_personalise_profile_reg_change is failed
  - '"Failed to unload registry hive at ANSIBLE" not in pri_personalise_profile_reg_change.msg'
  loop:
  - name: Hidden
    data: 1
  - name: HideFileExt
    data: 0

- name: disable screensaver for Server 2008 for the default user profile
  win_regedit:
    path: HKLM:\ANSIBLE\Control Panel\Desktop
    name: '{{item.name}}'
    data: '{{item.value|default(omit)}}'
    type: string
    state: '{{item.state}}'
    hive: C:\Users\Default\NTUSER.dat
  register: pri_personalise_screensaver_reg_change
  failed_when:
  - pri_personalise_screensaver_reg_change is failed
  - '"Failed to unload registry hive at ANSIBLE" not in pri_personalise_screensaver_reg_change.msg'
  when: man_host_type == '2008-x86' or man_host_type == '2008-x64'
  loop:
  - name: ScreenSaveActive
    state: present
    value: 0
  - name: SCRNSAVE.EXE
    state: absent

- name: check if ANSIBLE key was successfully unloaded
  win_reg_stat:
    path: HKLM:\ANSIBLE
  register: pri_personalise_reg_ansible_stat

- name: unload ANSIBLE key
  win_command: reg.exe unload HKLM\ANSIBLE
  when: pri_personalise_reg_ansible_stat.exists == True

- name: set show hidden files/folders and file extensions for the current user profile
  win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: '{{item.name}}'
    data: '{{item.data}}'
    type: dword
    state: present
  loop:
  - name: Hidden
    data: 1
  - name: HideFileExt
    data: 0

- name: disable screensaver for Server 2008 for the current user profile
  win_regedit:
    path: HKCU:\Control Panel\Desktop
    name: '{{item.name}}'
    data: '{{item.value|default(omit)}}'
    type: string
    state: '{{item.state}}'
  when: man_host_type == '2008-x86' or man_host_type == '2008-x64'
  loop:
  - name: ScreenSaveActive
    state: present
    value: 0
  - name: SCRNSAVE.EXE
    state: absent

- name: disable automatic updates (prevents TrustedInstaller startup thrash on older images)
  win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
    name: NoAutoUpdate
    data: 1
    type: dword
    state: present

- name: install sysinternals and vim
  win_chocolatey:
    name: '{{item}}'
    state: present
  loop:
  - sysinternals
  - vim

- name: install the VirtualBox Guest Additions
  include_tasks: virtualbox.yml
  when: man_provider == 'virtualbox'
