---
- name: set show hidden files/folders and file extensions for the default user profile
  win_regedit:
    path: HKLM:\ANSIBLE\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: '{{item.name}}'
    data: '{{item.data}}'
    type: dword
    state: present
    hive: C:\Users\Default\NTUSER.dat
  register: pri_personalise_profile_reg_change
  # seems like this fails to unload in Packer for whatever reason, we don't want to fail if we got that error
  failed_when:
  - pri_personalise_profile_reg_change is failed
  - '"Failed to unload registry hive at ANSIBLE" not in pri_personalise_profile_reg_change.msg'
  loop:
  - name: Hidden
    data: 1
  - name: HideFileExt
    data: 0

- name: disable screensaver for Server 2008 for the default user profile
  win_regedit:
    path: HKLM:\ANSIBLE\Control Panel\Desktop
    name: '{{item.name}}'
    data: '{{item.value|default(omit)}}'
    type: string
    state: '{{item.state}}'
    hive: C:\Users\Default\NTUSER.dat
  register: pri_personalise_screensaver_reg_change
  failed_when:
  - pri_personalise_screensaver_reg_change is failed
  - '"Failed to unload registry hive at ANSIBLE" not in pri_personalise_screensaver_reg_change.msg'
  when: man_host_type == '2008-x86' or man_host_type == '2008-x64'
  loop:
  - name: ScreenSaveActive
    state: present
    value: 0
  - name: SCRNSAVE.EXE
    state: absent

- name: check if ANSIBLE key was successfully unloaded
  win_reg_stat:
    path: HKLM:\ANSIBLE
  register: pri_personalise_reg_ansible_stat

- name: unload ANSIBLE key
  win_command: reg.exe unload HKLM\ANSIBLE
  when: pri_personalise_reg_ansible_stat.exists == True

- name: set show hidden files/folders and file extensions for the current user profile
  win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: '{{item.name}}'
    data: '{{item.data}}'
    type: dword
    state: present
  loop:
  - name: Hidden
    data: 1
  - name: HideFileExt
    data: 0

- name: disable screensaver for Server 2008 for the current user profile
  win_regedit:
    path: HKCU:\Control Panel\Desktop
    name: '{{item.name}}'
    data: '{{item.value|default(omit)}}'
    type: string
    state: '{{item.state}}'
  when: man_host_type == '2008-x86' or man_host_type == '2008-x64'
  loop:
  - name: ScreenSaveActive
    state: present
    value: 0
  - name: SCRNSAVE.EXE
    state: absent

- name: install procmon, procexp, pstools, and vim
  win_chocolatey:
    name: '{{item}}'
    state: present
  loop:
  - procmon
  - procexp
  - pstools
  - vim

- name: install the VirtualBox certificates required by the install process
  win_shell: |
    Get-ChildItem E:\cert\ -Filter vbox*.cer | ForEach-Object {
        E:\cert\VBoxCertUtil.exe add-trusted-publisher $_.FullName --root $_.FullName
    }

- name: install VirtualBox Guest Additions
  win_command: E:\VBoxWindowsAdditions.exe /force /with_autologon /with_d3d /with_wddm /S
  args:
    creates: C:\Program Files\Oracle\VirtualBox Guest Additions
  ignore_errors: yes
  register: pri_personalise_vbox_guest_install

- name: attempt to recover from failed install (Server 2008 needs to add 1 more cert to the trusted store)
  block:
  - name: install VBoxGuest.cat signer certificate
    win_shell: |
      $cert_file = "C:\Program Files\Oracle\VirtualBox Guest Additions\VBoxGuest.cat"
      $cert = (Get-AuthenticodeSignature -FilePath $cert_file).SignerCertificate

      $store_name = [System.Security.Cryptography.X509Certificates.StoreName]::TrustedPublisher
      $store_location = [System.Security.Cryptography.X509Certificates.StoreLocation]::LocalMachine
      $cert_store = New-Object -TypeName System.Security.Cryptography.X509Certificates.X509Store($store_name, $store_location)
      $cert_store.Open("MaxAllowed")
      $cert_store.Add($cert)
      $cert_store.Close()

  - name: add the VBoxGuest driver now it is trusted
    win_command: pnputil.exe -a "C:\Program Files\Oracle\VirtualBox Guest Additions\VBoxGuest.inf"

  - name: install VirtualBox Guest Additions again
    win_command: E:\VBoxWindowsAdditions.exe /force /with_autologon /with_d3d /with_wddm /S
  when: pri_personalise_vbox_guest_install.rc != 0

- name: install and enable TLSv1.2 for Server 2008 and 2008 R2
  include_tasks: tlsv1.2.yml
  when: man_host_type == '2008-x86' or man_host_type == '2008-x64' or man_host_type == '2008r2'
