---
- name: get windows update agent version for debugging purposes
  win_file_version:
    path: C:\Windows\System32\wuaueng.dll
  register: windows_update_agent_version

- name: windows update agent version
  debug:
    var: windows_update_agent_version

# This is a pretty ugly hack as there is no do until over a block of tasks. This
# will loop over the update and reboot task 10 times to cover all updates, the
# tasks in the loop are skipped when there are no updates which leads to a very
# minimal loss of time when all the updates are installed and we are still
# looping.
# We also set a dict that contains each category we loop through and whether we
# have exhausted the updates for the respective category. This is only done
# win_updates sometimes fails when too many updates need to be installed. This
# way each update block is split into smaller chunks.
- set_fact:
    update_stat:
    - name: CriticalUpdates
      finished: False
    - name: SecurityUpdates
      finished: False
    - name: Updates
      finished: False
    - name: UpdateRollups
      finished: False
    - name: FeaturePacks
      finished: False

- include_tasks: update.yml
  with_items: [1, 2, 3, 4, 5, 6, 7, 8, 9, 'end']
  loop_control:
    loop_var: loop_number
