# Server 2008, 2008 R2 and 2012 don't have cleanmgr setup by default, this
# needs to be copied from the relevant winsxs folder to it's intended location
# before running.
---
- name: copy cleanmgr from winsxs Server 2008 32-bit
  win_copy:
    src: C:\Windows\WinSxS\x86_microsoft-windows-cleanmgr_31bf3856ad364e35_6.0.6001.18000_none_6d4436615d8bd133\cleanmgr.exe
    dest: C:\Windows\System32\cleanmgr.exe
    remote_src: True
  when: man_host_type == "2008-x86"

- name: copy cleanmgr mui from winsxs Server 2008 32-bit
  win_copy:
    src: C:\Windows\WinSxS\x86_microsoft-windows-cleanmgr.resources_31bf3856ad364e35_6.0.6001.18000_en-us_5dd66fed98a6c5bc\cleanmgr.exe.mui
    dest: C:\Windows\System32\en-US\cleanmgr.exe.mui
    remote_src: True
  when: man_host_type == "2008-x86"

- name: copy cleanmgr from winsxs Server 2008 64-bit
  win_copy:
    src: C:\Windows\WinSxS\amd64_microsoft-windows-cleanmgr_31bf3856ad364e35_6.0.6001.18000_none_c962d1e515e94269\cleanmgr.exe
    dest: C:\Windows\System32\cleanmgr.exe
    remote_src: True
  when: man_host_type == "2008-x64"

- name: copy cleanmgr mui from winsxs Server 2008 64-bit
  win_copy:
    src: C:\Windows\WinSxS\amd64_microsoft-windows-cleanmgr.resources_31bf3856ad364e35_6.0.6001.18000_en-us_b9f50b71510436f2\cleanmgr.exe.mui
    dest: C:\Windows\System32\en-US\cleanmgr.exe.mui
    remote_src: True
  when: man_host_type == "2008-x64"

- name: copy cleanmgr from winsxs Server 2008 R2
  win_copy:
    src: C:\Windows\WinSxS\amd64_microsoft-windows-cleanmgr_31bf3856ad364e35_6.1.7600.16385_none_c9392808773cd7da\cleanmgr.exe
    dest: C:\Windows\System32\cleanmgr.exe
    remote_src: True
  when: man_host_type == "2008r2"

- name: copy cleanmgr mui from winsxs Server 2008 R2
  win_copy:
    src: C:\Windows\WinSxS\amd64_microsoft-windows-cleanmgr.resources_31bf3856ad364e35_6.1.7600.16385_en-us_b9cb6194b257cc63\cleanmgr.exe.mui
    dest: C:\Windows\System32\en-US\cleanmgr.exe.mui
    remote_src: True
  when: man_host_type == "2008r2"

# Cannot use win_hotfix as DISM cmdlets are not available with Server 2008 R2
- name: check if Server 2008 R2 hotfix for Windows update cleanup is installed
  win_command: DISM.exe /Online /Get-PackageInfo /PackageName:"Package_for_KB2852386~31bf3856ad364e35~amd64~~6.1.2.1"
  register: pri_cleanup_winsxs_dism_hotfix_check
  when: man_host_type == "2008r2"
  failed_when: False

- block:
  - name: download hotfix to enable Windows update cleanup
    win_get_url:
      url: https://download.microsoft.com/download/2/A/3/2A3FD850-E45F-47D4-AFF8-8048333CBA7D/Windows6.1-KB2852386-v2-x64.msu
      dest: C:\temp\Windows6.1-KB2852386-v2-x64.msu

  - name: install hotfix to enable Windows Update cleanup on Server 2008 R2
    win_command: C:\temp\WIndows6.1-KB2852386-v2-x64.msu /quiet /norestart
    become: yes

  - name: reboot server after installing hotfix
    win_reboot:
  when: pri_cleanup_winsxs_dism_hotfix_check.rc is defined and pri_cleanup_winsxs_dism_hotfix_check.rc != 0

- name: copy cleanmgr from winsxs Server 2012
  win_copy:
    src: C:\Windows\WinSxS\amd64_microsoft-windows-cleanmgr_31bf3856ad364e35_6.2.9200.16384_none_c60dddc5e750072a\cleanmgr.exe
    dest: C:\Windows\System32\cleanmgr.exe
    remote_src: True
  when: man_host_type == "2012"

- name: copy cleanmgr mui from winsxs Server 2012
  win_copy:
    src: C:\Windows\WinSxS\amd64_microsoft-windows-cleanmgr.resources_31bf3856ad364e35_6.2.9200.16384_en-us_b6a01752226afbb3\cleanmgr.exe.mui
    dest: C:\Windows\System32\en-US\cleanmgr.exe.mui
    remote_src: True
  when: man_host_type == "2012"

- name: run cleanmgr with everything set
  block:
  - name: set custom flags for cleanmgr run
    win_shell: |
      $volume_caches = Get-ChildItem -Path "HKLM:\Software\Microsoft\Windows\CurrentVersion\Explorer\VolumeCaches"
      foreach ($volume_cache in $volume_caches) {
          New-ItemProperty -Path $volume_cache.PSPath -Name StateFlags0666 -Value 2 -Type DWORD -Force | Out-Null
      }

  - name: run cleanmgr with custom flag
    win_command: cleanmgr.exe /sagerun:666
  
  always:
  - name: clear custom flags after cleanmgr run
    win_shell: |
      $volume_caches = Get-ChildItem -Path "HKLM:\Software\Microsoft\Windows\CurrentVersion\Explorer\VolumeCaches"
      foreach ($volume_cache in $volume_caches) {
          Remove-ItemProperty -Path $volume_cache.PSPath -Name StateFlags0666 -Force | Out-Null
      }
