---
- name: determine if host supports DISM with reset base
  win_shell: |
    $version = [Environment]::OSVersion.Version
    $major = $version.Major
    $minor = $version.Minor
    if ($major -eq 6) {
        if ($minor -gt 2) {
            "true"
        } else {
            "false"
        }
    } elseif ($major -gt 6) {
        "true"
    } else {
        "false"
    }
  register: dism_supported

- name: run DISM with reset base on hosts that support it
  win_command: DISM.exe /Online /Cleanup-Image /StartComponentCleanup /ResetBase
  when: dism_supported.stdout_lines[0] == "true"

- name: run DISM to clear service packs when not Server 2008
  win_command: DISM.exe /Online /Cleanup-Image /SPSuperseded
  when: os_version.stdout_lines[0] != '6.0-x86' and os_version.stdout_lines[0] != '6.0-AMD64'

- name: run compcln to clear service packs for Server 2008
  win_command: compcln.exe /quiet
  register: compcln_result
  when: os_version.stdout_lines[0] == '6.0-x86' or os_version.stdout_lines[0] == '6.0-AMD64'
  failed_when: compcln_result.rc != 0 and compcln_result.rc != -2147467259 # 0 is good the other is already run

- name: setup and run cleanmgr if DISM reset base wasn't supported
  include_tasks: cleanmgr.yml
  when: dism_supported.stdout_lines[0] == "false"
