---
- name: determine if host supports DISM
  win_shell: |
    $version = [Environment]::OSVersion.Version
    $major = $version.Major
    $minor = $version.Minor
    if ($major -eq 6) {
        if ($minor -gt 1) {
            "true"
        } else {
            "false"
        }
    } elseif ($major -gt 6) {
        "true"
    } else {
        "false"
    }
  register: dism_supported

- name: run DISM cleanup if supported
  win_command: DISM.exe /Online /Cleanup-Image /StartComponentCleanup /ResetBase
  when: dism_supported.stdout_lines[0] == "true"

# old DISM, might need windows-adk
# DISM.exe /Online /Cleanup-Image /spsuperseded

- name: check if cleanmgr.exe is set in System32
  win_stat:
    path: C:\Windows\System32\cleanmgr.exe
  register: cleanmgr_stat

- name: copy cleanmgr from winsxs Server 2008 32-bit
  win_copy:
    src: C:\Windows\winsxs\x86_microsoft-windows-cleanmgr_31bf3856ad364e35_6.0.6001.18000_none_6d4436615d8bd133\cleanmgr.exe
    dest: C:\Windows\System32\cleanmgr.exe
    remote_src: True
  when: cleanmgr_stat.stat.exists == False and os_version.stdout_lines[0] == '6.0-x86'

- name: copy cleanmgr mui from winsxs Server 2008 32-bit
  win_copy:
    src: C:\Windows\winsxs\x86_microsoft-windows-cleanmgr.resources_31bf3856ad364e35_6.0.6001.18000_en-us_5dd66fed98a6c5bc\cleanmgr.exe.mui
    dest: C:\Windows\System32\en-US\cleanmgr.exe.mui
    remote_src: true
  when: cleanmgr_stat.stat.exists == False and os_version.stdout_lines[0] == '6.0-x86'

- name: copy cleanmgr from winsxs Server 2008 64-bit
  win_copy:
    src: C:\Windows\winsxs\amd64_microsoft-windows-cleanmgr_31bf3856ad364e35_6.0.6001.18000_none_c962d1e515e94269\cleanmgr.exe
    dest: C:\Windows\System32\cleanmgr.exe
    remote_src: True
  when: cleanmgr_stat.stat.exists == False and os_version.stdout_lines[0] == '6.0-AMD64'

- name: copy cleanmgr mui from winsxs Server 2008 64-bit
  win_copy:
    src: C:\Windows\winsxs\amd64_microsoft-windows-cleanmgr.resources_31bf3856ad364e35_6.0.6001.18000_en-us_b9f50b71510436f2\cleanmgr.exe.mui
    dest: C:\Windows\System32\en-US\cleanmgr.exe.mui
    remote_src: true
  when: cleanmgr_stat.stat.exists == False and os_version.stdout_lines[0] == '6.0-AMD64'

- name: copy cleanmgr from winsxs Server 2008 R2
  win_copy:
    src: C:\Windows\winsxs\amd64_microsoft-windows-cleanmgr_31bf3856ad364e35_6.1.7600.16385_none_c9392808773cd7da\cleanmgr.exe
    dest: C:\Windows\System32\cleanmgr.exe
    remote_src: True
  when: cleanmgr_stat.stat.exists == False and os_version.stdout_lines[0] == '6.1-AMD64'

- name: copy cleanmgr mui from winsxs Server 2008 R2
  win_copy:
    src: C:\Windows\winsxs\amd64_microsoft-windows-cleanmgr.resources_31bf3856ad364e35_6.1.7600.16385_en-us_b9cb6194b257cc63\cleanmgr.exe.mui
    dest: C:\Windows\System32\en-US\cleanmgr.exe.mui
    remote_src: true
  when: cleanmgr_stat.stat.exists == False and os_version.stdout_lines[0] == '6.1-AMD64'

# this seems to hang as a dialogue box is opened right at the end
#- name: run cleanmgr to cleanup disk
#  win_command: cleanmgr.exe /VERYLOWDISK
