---
- name: ensure unattend panther and temp directory exists
  win_file:
    path: '{{item}}'
    state: directory
  with_items:
  - C:\Windows\Panther\Unattend
  - C:\temp

- name: download the Ansible ConfigureRemotingForAnsible.ps1 script
  win_get_url:
    url: https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1
    dest: C:\temp\ConfigureRemotingForAnsible.ps1

- name: template the unattend.xml file
  win_template:
    src: unattend.xml.tmpl
    dest: C:\Windows\Panther\Unattend\unattend.xml

- name: set flag to recreate pagefile after next sysprep
  win_shell: |
    $system = Get-WmiObject -Class Win32_ComputerSystem -EnableAllPrivileges
    if ($system -ne $null) {
        $system.AutomaticManagedPagefile = $true
        $system.Put()
    }
