---
- name: ensure unattend panther and temp directory exists
  win_file:
    path: '{{item}}'
    state: directory
  loop:
  - C:\Windows\Panther\Unattend
  - C:\temp

- name: create PackerWindoze PowerShell module folder
  win_file:
    path: C:\Program Files\WindowsPowerShell\Modules\PackerWindoze\{{man_packer_windoze_version}}
    state: directory

- name: copy across the PackerWindoze manifest file
  win_copy:
    src: PackerWindoze.psm1
    dest: C:\Program Files\WindowsPowerShell\Modules\PackerWindoze\{{man_packer_windoze_version}}\PackerWindoze.psm1

- name: template across the PackerWindoze definition file
  win_template:
    src: PackerWindoze.psd1
    dest: C:\Program Files\WindowsPowerShell\Modules\PackerWindoze\{{man_packer_windoze_version}}\PackerWindoze.psd1

- name: template the unattend.xml file
  win_template:
    src: unattend.xml.tmpl
    dest: C:\Windows\Panther\Unattend\unattend.xml

- name: copy across the sysprep powershell script
  win_template:
    src: setup.ps1.tmpl
    dest: C:\temp\setup.ps1

- name: create scheduled task to delete WinRM listeners and shutdown
  win_scheduled_task:
    name: packer-shutdown
    username: SYSTEM
    disallow_start_if_on_batteries: no
    stop_if_going_on_batteries: no
    actions:
    - path: powershell.exe
      arguments: Remove-Item -Path WSMan:\localhost\Listener\* -Recurse -Force
    - path: C:\windows\system32\sysprep\sysprep.exe
      arguments: /generalize /oobe /quiet /shutdown /unattend:C:\Windows\Panther\Unattend\unattend.xml

- name: set flag to recreate pagefile after next sysprep
  win_shell: |
    $system = Get-WmiObject -Class Win32_ComputerSystem -EnableAllPrivileges
    if ($system -ne $null) {
        $system.AutomaticManagedPagefile = $true
        $system.Put()
    }
